services:
  api:
    build:
      context: .
      dockerfile: CodeLifeAcademy.API/Dockerfile
    expose:
      - "80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=codelifeacademy.ru,www.codelifeacademy.ru
      - LETSENCRYPT_HOST=codelifeacademy.ru,www.codelifeacademy.ru
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: codelife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: mvtvr21@yandex.ru
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - web 


volumes:
  db-data:

networks:
  web:
    driver: bridge

